n_pts: 5
image_folder: '.'
label_folder: '.'
patterns: ['*.png', '*.jpg']

# Parameters
decimal_precision: 3
init_scale: 1.0
scale_limit: [0.5, 4.0]
line_width: 1
point_radius: 4
point_select_thresh: 6
line_select_thresh: 5
window_size: [1920, 1080]
default_image_size: [1024, 1024]

# Shortcuts
menu_OpenDir_shortcut: 'Ctrl+O'
menu_Save_shortcut: 'Ctrl+S'
menu_Next_shortcut: 'Ctrl+V'
menu_Prev_shortcut: 'Ctrl+B'
menu_Create_shortcut: 'Ctrl+C'
menu_Delete_shortcut: 'Ctrl+D'
menu_Tutorial_shortcut: 'Ctrl+U'